//
// Created by justinw on 10/03/2026.
//

#ifndef TYPHON_COMMON_H
#define TYPHON_COMMON_H

enum Precedence {
    NONE,
    ASSIGNMENT,
    OR,
    AND,
    EQUALITY,
    COMPARISON,
    TERM,
    FACTOR,
    EXPONENT,
    UNARY,
    CALL,
    PRIMARY
};

enum class NodeKind {
    TYPE, PARAMETER, BODY, FUNCTION, EXT_FUNCTION, CLASS, BINARY_EXPR, UNARY_EXPR, IF, WHILE, FOR, IDENTIFIER, LITERAL,
    FUNC_CALL, GET_EXPR, COMP_ASSIGN_EXPR, COMP_SET_EXPR, ASSIGN_EXPR, RETURN_EXPR
};

enum class Visibility {
    PUBLIC, PRIVATE, INTERNAL
};

#endif //TYPHON_COMMON_H